language: python

python:
  - "3.6"
  - "3.5"
  - "2.7"
  - "pypy"


# See https://github.com/travis-ci/travis-ci/issues/9815
matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true

env:
  - AWS_SECRET_ACCESS_KEY=fake_key AWS_ACCESS_KEY_ID=fake_id

install:
  - pip install -e .[signals] -r requirements-dev.txt

before_script:
  - wget http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest.tar.gz -O /tmp/dynamodb_local_latest.tar.gz
  - tar -xzf /tmp/dynamodb_local_latest.tar.gz -C /tmp
  - java -Djava.library.path=/tmp/DynamoDBLocal_lib -jar /tmp/DynamoDBLocal.jar -inMemory -port 8000 &
  - sleep 2

script:
  - pytest --cov-report term-missing --cov=pynamodb tests
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.7" ]]; then mypy .; fi
  - sphinx-build -W docs /tmp/docs-build

after_success:
  - coveralls

deploy:
  provider: pypi
  user: lyft-pynamodb
  edge: true
  password:
    secure: "B2AAd62kRYOiCcLjhfIJsICS9laH9J9c5H4tU2C2Vojnb+3W/qj9xP+/GnEZ6Tc2h4SNMQ81Wtzn1CjD3Ut8CCudoBKSZnJmip+EACgpNXjZiU+g0PlEgVbDfJV15OrmFGUeDexxLF3DEQKp8YiMpAhJAH6+SV5W17Er1M6mwBs="
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = 3.7
